# Generated by Django 6.1.1 on 2026-10-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Online Job', 'Online Job'), ('Nearby Job', 'Nearby Job'), ('Work From Home', 'Work From Home'), ('Part Time Job', 'Part Time Job'), ('Full Time Job', 'Full Time Job')], max_length=50)),
                ('work_mode', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('application_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('Spa Centre', 'Spa Centre'), ('Massage', 'Massage')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('price_from', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
